[Service]
ExecStart=
ExecStart=/bin/bash -c "source /opt/ros/noetic/setup.bash; source /home/wheeltec/wheeltec_robot/devel/setup.bash; exec roslaunch turn_on_wheeltec_robot turn_on_wheeltec_robot.launch car_mode:=mini_mec_moveit_four"
